server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # React SPA — toutes les routes vers index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend FastAPI
    location /sda-api/ {
        proxy_pass http://sda-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy vers Syncthing (avec injection de la clé API)
    # Note: DNS Docker Compose = nom du service ("syncthing"), pas container_name ("sda-syncthing")
    location /syncthing-api/ {
        proxy_pass http://syncthing:8384/;
        proxy_set_header Host $host;
        proxy_set_header X-API-Key "FhrJ56rUqDmMejwqSYh5mRsntGMCWSqQ";
        proxy_set_header X-Real-IP $remote_addr;
    }
}
